name: Test Workflow

on:
  workflow_dispatch:   # lets you run it manually

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
